version: "2.1"
services: 
  vrising:
    container_name: vrising-server
    image: vrising:latest
    volumes: 
      - /home/googlrr/VRisingServer:/root/.wine/drive_c/users/root/AppData/LocalLow/Stunlock Studios/VRisingServer/Saves
      - /home/googlrr/VRisingSettings:/root/.wine/drive_c/users/root/AppData/LocalLow/Stunlock Studios/VRisingServer/Settings/
    ports: 
      - "9876:9876/udp"
      - "9877:9877/udp"
    restart: unless-stopped
    tty: true