name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file dockerfile --tag vix1994/vrising-server:latest
           
    - name: Log in registry
      run: echo "${{ secrets.REGISTRY_ACCESS_TOKEN }}" | docker login -u vix1994 --password-stdin
      
    - name: Push to registry
      run: docker push vix1994/vrising-server:latest